from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from fpdf import FPDF
from io import BytesIO
from app.db.chat_store import get_conversation_messages, get_conversations

router = APIRouter()


def safe_text(text: str) -> str:
    return text.encode("latin-1", "replace").decode("latin-1")


@router.get("/conversations/{conversation_id}/export")
async def export_conversation_pdf(conversation_id: str):
    messages = await get_conversation_messages(conversation_id)
    if not messages:
        raise HTTPException(status_code=404, detail="Conversation not found")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    page_width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(page_width, 10, "MediSearch AI - Chat Export", ln=True, align="C")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(128, 128, 128)
    if messages:
        pdf.cell(page_width, 5, f"Conversation ID: {conversation_id}", ln=True)
    pdf.ln(5)

    for msg in messages:
        role = msg["role"].capitalize()
        content = msg["content"]

        if msg["role"] == "user":
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 102, 204)
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)

        pdf.set_x(pdf.l_margin)
        pdf.cell(page_width, 6, f"{role}:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(33, 33, 33)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(page_width, 5, safe_text(content))
        pdf.ln(3)

        if msg.get("sources"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.set_x(pdf.l_margin)
            pdf.cell(page_width, 5, "Sources:", ln=True)
            for src in msg["sources"]:
                title = src.get("title", "Unknown")[:70]
                pmid = src.get("pmid", "")
                line = f"[{src.get('source_number', '')}] {title} (PMID: {pmid})"
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(page_width, 4, safe_text(line))
            pdf.ln(3)

    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(150, 150, 150)
    pdf.set_x(pdf.l_margin)
    pdf.cell(page_width, 10, "Generated by MediSearch AI", ln=True, align="C")

    buffer = BytesIO()
    pdf.output(buffer)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename=medisearch_chat_{conversation_id[:8]}.pdf"
        },
    )
